server:
  port: 8092
  servlet:
    context-path: /basicdata
spring:
  application:
    name: hl-basicdata
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: ${DB_CONN:jdbc:mysql://127.0.0.1:13306/hl_basicdata?autoReconnect=true}
    username: root
    password: qwe!P4ss
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://service1:8000/eureka}
swagger:
  title: hl-basicdata
  description: 提供基础数据服务相关接口
  version: v1.0.0
  enable: true
  controller-package-name: com.liuhll.hl.basicdata.controller

auth:
  service-id: hl-auth
  client:
    id: hl-basicdata
    secret: 1234567
  user:
    token-header: Authorization
    jwt-secret: qY9Z3TMrSoqiolNQcgTYkkvCzN62ArNHL3XgtDww86X9WZGO6cAo7cz3yQX0qeJj
