server:
  port: 8091
  servlet:
    context-path: /product
spring:
  application:
    name: hl-product
  profiles:
    active: ${HL_ENV:dev}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: ${DB_CONN:jdbc:mysql://127.0.0.1:13306/hl_product?autoReconnect=true}
    username: root
    password: qwe!P4ss
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://service1:8000/eureka}

swagger:
  title: hl-product
  description: 提供产品相关服务接口
  version: v1.0.0
  enable: true
  controller-package-name: com.liuhll.hl.product.controller

auth:
  service-id: hl-auth
  client:
    id: hl-product
    secret: 1234567
  user:
    token-header: Authorization
    jwt-secret: qY9Z3TMrSoqiolNQcgTYkkvCzN62ArNHL3XgtDww86X9WZGO6cAo7cz3yQX0qeJj
