server:
  port: 8091
  servlet:
    context-path: /product
spring:
  application:
    name: hl-product
  profiles:
    active: ${HL_ENV:dev}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/product_data?autoReconnect=true
    username: root
    password: qwe!P4ss
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://service1:8000/eureka}

swagger:
  title: 产品服务组件
  description: 提供产品相关服务接口
  version: v1.0.0
  enable: true
  controller-package-name: com.liuhll.hl.product.controller
