server:
  port: 8080
  servlet:
    context-path: /product
spring:
  application:
    name: hl-product
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/product_data?autoReconnect=true
    username: root
    password: qwe!P4ss
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://service1:8000/eureka}
