server:
  port: 8093
  servlet:
    context-path: /organization
spring:
  application:
    name: hl-organization
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/organizetion_db?autoReconnect=true
    username: root
    password: qwe!P4ss
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://service1:8000/eureka}
swagger:
  title: 组织机构服务组件
  description: 提供组织机构服务相关结构
  version: v1.0.0
  enable: true
  controller-package-name: com.liuhll.hl.organization.controller
