server:
  port: 8093
  servlet:
    context-path: /organization
spring:
  application:
    name: hl-organization
  profiles:
    active: ${HL_ENV:dev}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/organizetion_db?autoReconnect=true
    username: root
    password: qwe!P4ss
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://service1:8000/eureka}

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000

swagger:
  title: hl-organization
  description: 提供组织机构服务相关结构
  version: v1.0.0
  enable: true
  controller-package-name: com.liuhll.hl.organization.controller

auth:
  service-id: hl-identity
#  whitelist:
#    - /organization/v1/api/org
  client:
    id: hl-organization
    secret: 1234567
  user:
    token-header: Authorization
    jwt-secret: qY9Z3TMrSoqiolNQcgTYkkvCzN62ArNHL3XgtDww86X9WZGO6cAo7cz3yQX0qeJj
