server:
  port: 8090
  servlet:
    context-path: /auth
spring:
  application:
    name: hl-auth
  profiles:
    active: ${HL_ENV:dev}
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate.format_sql: true
#    open-in-view: false
  datasource:
    url: ${DB_CONN:jdbc:mysql://127.0.0.1:13306/hl_identity?autoReconnect=true&useUnicode=true&characterEncoding=UTF8}
    username: root
    password: qwe!P4ss
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://service1:8000/eureka}

swagger:
  title: hl-auth
  description: 提供用户登录、身份认证与授权相关接口
  version: v1.0.0
  enable: true
  controller-package-name: com.liuhll.hl.auth.controller

auth:
  whitelist:
    - /v1/login
    - /v1/service/allowedclients
    - /v1/service/jwtsecret
  service-id: hl-auth
  client:
    id: hl-auth
    secret: 1234567
  token-header: Authorization

mybatis:
  type-aliases-package: com.liuhll.hl.auth.domain.entity
  mapperLocations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mapper:
  not-empty: false
  identity: MYSQL

jwt:
  secret: qY9Z3TMrSoqiolNQcgTYkkvCzN62ArNHL3XgtDww86X9WZGO6cAo7cz3yQX0qeJj
  expiration: 1000000

