spring:
  application:
    name: hl-zuul-gateway
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SEVICE_URLS:http://service1:8000/eureka}
zuul:
  routes:
    ignored-services: "*"
    sensitive-headers: Cookie,Set-Cookie
    hl-auth:
      path: /auth/**
      serviceId: hl-auth
      strip-prefix: false
auth:
  service-id: hl-auth
  token-header: token
  #  whitelist:
  #    - /organization/v1/api/org
  client:
    id: hl-gateway
    secret: 123456
